# Generated by Django 4.2.18 on 2025-03-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('smiles', models.CharField(max_length=1000, null=True)),
                ('cas', models.CharField(blank=True, max_length=100, null=True)),
                ('prediction', models.FloatField(null=True)),
                ('efficiency', models.CharField(max_length=100, null=True)),
                ('molecule_image', models.TextField(null=True)),
                ('formula', models.CharField(max_length=100, null=True)),
                ('iupac_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('properties', models.JSONField(null=True)),
                ('descriptors', models.JSONField(null=True)),
                ('shap_plot', models.TextField(blank=True, null=True)),
                ('plot_all', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
