# Generated by Django 4.2.18 on 2025-03-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='inputType',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
