# Generated by Django 4.2.18 on 2025-03-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_predictionhistory_inputtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionhistory',
            old_name='inputType',
            new_name='model_name',
        ),
    ]
