# Generated by Django 4.2.18 on 2025-03-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_inputtype_predictionhistory_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='atom_scores',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='token_scores',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='xsmiles_data',
            field=models.TextField(null=True),
        ),
    ]
