# Generated by Django 4.2.18 on 2025-04-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_predictionhistory_atom_scores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='atom_scores',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='token_scores',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='xsmiles_data',
        ),
    ]
