# Generated by Django 4.2.18 on 2025-04-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_predictionhistory_atom_scores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='plot_all',
        ),
    ]
